// Code generated by avrogen. DO NOT EDIT.

package linkedListThenSomethingElse

import (
	"github.com/arenko-group/avro/avrotypegen"
)

type List struct {
	Item int
	Next *List
}

// AvroRecord implements the avro.AvroRecord interface.
func (List) AvroRecord() avrotypegen.RecordInfo {
	return avrotypegen.RecordInfo{
		Schema: `{"fields":[{"name":"Item","type":"int"},{"default":null,"name":"Next","type":["null","List"]}],"name":"List","type":"record"}`,
		Required: []bool{
			0: true,
		},
	}
}

type R struct {
	L List
	M int
}

// AvroRecord implements the avro.AvroRecord interface.
func (R) AvroRecord() avrotypegen.RecordInfo {
	return avrotypegen.RecordInfo{
		Schema: `{"fields":[{"name":"L","type":{"fields":[{"name":"Item","type":"int"},{"default":null,"name":"Next","type":["null","List"]}],"name":"List","type":"record"}},{"name":"M","type":"int"}],"name":"R","type":"record"}`,
		Required: []bool{
			0: true,
			1: true,
		},
	}
}
